# Generated by Django 3.2 on 2025-02-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_revokedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
