# Generated by Django 3.2 on 2025-02-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessnumbergame',
            name='reward_given',
            field=models.BooleanField(default=False),
        ),
    ]
