# Generated by Django 3.2 on 2025-02-20 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_box_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('county', models.CharField(choices=[('Alba', 'Alba'), ('Arad', 'Arad'), ('Argeș', 'Argeș'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Brăila', 'Brăila'), ('București', 'București'), ('Buzău', 'Buzău'), ('Caraș-Severin', 'Caraș-Severin'), ('Călărași', 'Călărași'), ('Cluj', 'Cluj'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Gorj', 'Gorj'), ('Harghita', 'Harghita'), ('Hunedoara', 'Hunedoara'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Ilfov', 'Ilfov'), ('Maramureș', 'Maramureș'), ('Mehedinți', 'Mehedinți'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Satu Mare', 'Satu Mare'), ('Sălaj', 'Sălaj'), ('Sibiu', 'Sibiu'), ('Suceava', 'Suceava'), ('Teleorman', 'Teleorman'), ('Timiș', 'Timiș'), ('Tulcea', 'Tulcea'), ('Vaslui', 'Vaslui'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea')], default='Suceava', max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('commune', models.CharField(blank=True, max_length=255, null=True)),
                ('waiting', models.BooleanField(default=False)),
                ('package_box', models.ForeignKey(blank=True, help_text='Cutia asociată comenzii', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_new_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('main_image', models.URLField(max_length=500)),
                ('secondary_images', models.JSONField(blank=True, help_text='Listă de URL-uri ale imaginilor', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('product_price', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('external_id', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_new.order')),
            ],
        ),
    ]
