# Generated by Django 3.2 on 2025-02-20 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_box_code'),
        ('store_new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.box')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_new.order')),
            ],
        ),
        migrations.CreateModel(
            name='BoxQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_queue', to='store_new.order')),
            ],
        ),
    ]
