# Generated by Django 3.2 on 2025-02-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_new', '0003_coincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalCoinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Cod generat de 3 caractere', max_length=3, unique=True)),
                ('total_amount', models.PositiveIntegerField(help_text='Total coins disponibile (uses * coins_per_use + 1)')),
                ('max_withdrawal', models.PositiveIntegerField(help_text='Valoarea maximă ce se poate extrage la fiecare redeem')),
            ],
        ),
    ]
