# Generated by Django 3.2 on 2025-02-26 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_new', '0004_withdrawalcoincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinCode',
        ),
    ]
