# Generated by Django 3.2 on 2025-02-19 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('nume_custom', models.CharField(max_length=50, unique=True)),
                ('tip_sectie', models.CharField(choices=[('depozit', 'Depozit'), ('livrare', 'Zona de Livrare'), ('receptie', 'Zona de Recepție'), ('procesare', 'Procesare'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('max_capacity', models.IntegerField()),
                ('current_capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('albastru', 'Albastru'), ('rosu', 'Rosu'), ('verde', 'Verde'), ('simple', 'Bej')], max_length=10)),
                ('status', models.CharField(choices=[('sold', 'Sold'), ('in_stoc', 'In Stoc')], default='in_stoc', max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='box_images/default.jpg', null=True, upload_to='box_images/')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.section')),
            ],
            options={
                'ordering': ['color', 'code', 'price'],
            },
        ),
    ]
